INSERT INTO category values ('Animals');
INSERT INTO category values ('Birds');
INSERT INTO category values ('Foods');
INSERT INTO category values ('Fruits');
INSERT INTO category values ('Letters');
INSERT INTO category values ('Numbers');
INSERT INTO category values ('Relatives');
INSERT INTO category values ('Shapes');
INSERT INTO category values ('Sounds');
INSERT INTO category values ('Things with buttons');
INSERT INTO category values ('Toys');
INSERT INTO category values ('Vegetables');
INSERT INTO category values ('Classroom Objects');
INSERT INTO category values ('Clothing');
INSERT INTO category values ('Condiments');
INSERT INTO category values ('Drinks');
INSERT INTO category values ('Electronic Goods');
INSERT INTO category values ('Kitchen Utensils');
INSERT INTO category values ('Musical Instruments');
INSERT INTO category values ('School Subjects');
INSERT INTO category values ('Sports/Games');
INSERT INTO category values ('Television');
INSERT INTO category values ('Things at the Beach');
INSERT INTO category values ('Things with Pockets');
INSERT INTO category values ('Things with Wheels');
INSERT INTO category values ('Tools');
INSERT INTO category values ('Transportation');
INSERT INTO category values ('Types of Breakfast');
INSERT INTO category values ('Bathroom Items');
INSERT INTO category values ('Bedroom Items');
INSERT INTO category values ('Cars');
INSERT INTO category values ('Comic book heroes');
INSERT INTO category values ('Dairy products');
INSERT INTO category values ('Fast food');
INSERT INTO category values ('Furniture');
INSERT INTO category values ('Junk food');
INSERT INTO category values ('Liquids');
INSERT INTO category values ('Materials');
INSERT INTO category values ('Movies');
INSERT INTO category values ('Board Games');
INSERT INTO category values ('Cuisine');
INSERT INTO category values ('Gardening');
INSERT INTO category values ('Gasses');
INSERT INTO category values ('Internal organs');
INSERT INTO category values ('Recipes');
INSERT INTO category values ('Technology');
